"""drop emotions.message_id

Revision ID: 66733ca14bad
Revises: 74a16744158e
Create Date: 2026-05-23 03:57:31.052702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66733ca14bad'
down_revision: Union[str, None] = '74a16744158e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('emotions_message_id_fkey', 'emotions', schema='emotion_extraction_chat', type_='foreignkey')
    op.drop_column('emotions', 'message_id', schema='emotion_extraction_chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotions', sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=True), schema='emotion_extraction_chat')
    op.create_foreign_key('emotions_message_id_fkey', 'emotions', 'messages', ['message_id'], ['id'], source_schema='emotion_extraction_chat', referent_schema='emotion_extraction_chat', ondelete='SET NULL')
    # ### end Alembic commands ###
