"""initial schema

Revision ID: 74a16744158e
Revises: 
Create Date: 2026-05-22 17:24:47.402713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a16744158e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='emotion_extraction_chat'
    )
    op.create_index(op.f('ix_emotion_extraction_chat_users_email'), 'users', ['email'], unique=True, schema='emotion_extraction_chat')
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'analyzed', name='conversation_status', schema='emotion_extraction_chat', inherit_schema=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['emotion_extraction_chat.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='emotion_extraction_chat'
    )
    op.create_index(op.f('ix_emotion_extraction_chat_conversations_user_id'), 'conversations', ['user_id'], unique=False, schema='emotion_extraction_chat')
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='message_role', schema='emotion_extraction_chat', inherit_schema=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['emotion_extraction_chat.conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='emotion_extraction_chat'
    )
    op.create_index(op.f('ix_emotion_extraction_chat_messages_conversation_id'), 'messages', ['conversation_id'], unique=False, schema='emotion_extraction_chat')
    op.create_table('emotions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.Enum('sadness', 'anxiety', 'anger', 'frustration', 'fear', 'guilt', 'shame', 'loneliness', 'disappointment', 'stress/overwhelm', name='emotion_label', schema='emotion_extraction_chat', inherit_schema=True), nullable=False),
    sa.Column('intensity', sa.Enum('low', 'medium', 'high', name='emotion_intensity', schema='emotion_extraction_chat', inherit_schema=True), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['emotion_extraction_chat.conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['emotion_extraction_chat.messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='emotion_extraction_chat'
    )
    op.create_index(op.f('ix_emotion_extraction_chat_emotions_conversation_id'), 'emotions', ['conversation_id'], unique=False, schema='emotion_extraction_chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emotion_extraction_chat_emotions_conversation_id'), table_name='emotions', schema='emotion_extraction_chat')
    op.drop_table('emotions', schema='emotion_extraction_chat')
    op.drop_index(op.f('ix_emotion_extraction_chat_messages_conversation_id'), table_name='messages', schema='emotion_extraction_chat')
    op.drop_table('messages', schema='emotion_extraction_chat')
    op.drop_index(op.f('ix_emotion_extraction_chat_conversations_user_id'), table_name='conversations', schema='emotion_extraction_chat')
    op.drop_table('conversations', schema='emotion_extraction_chat')
    op.drop_index(op.f('ix_emotion_extraction_chat_users_email'), table_name='users', schema='emotion_extraction_chat')
    op.drop_table('users', schema='emotion_extraction_chat')
    # Postgres keeps ENUM types after their tables are dropped; remove them
    # explicitly so a re-upgrade does not fail with "type already exists".
    for enum_name in ('emotion_intensity', 'emotion_label', 'message_role', 'conversation_status'):
        op.execute(f'DROP TYPE IF EXISTS emotion_extraction_chat.{enum_name}')
    # ### end Alembic commands ###
